// <auto-generated />
using System;
using System.Text.Json;
using Labubu.Main.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Labubu.Main.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20251109102245_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Labubu.Main.DAL.Achievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("Labubu.Main.DAL.AchievementProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AchievementId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LabubuId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AchievementId");

                    b.HasIndex("LabubuId");

                    b.ToTable("AchievementProgresses");
                });

            modelBuilder.Entity("Labubu.Main.DAL.Clothes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clothes");
                });

            modelBuilder.Entity("Labubu.Main.DAL.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Labubu.Main.DAL.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Award")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LabubuId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Score")
                        .HasColumnType("integer");

                    b.Property<JsonDocument>("SpecificData")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("LabubuId");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("Labubu.Main.DAL.Labubu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Energy")
                        .HasColumnType("integer");

                    b.Property<int>("Health")
                        .HasColumnType("integer");

                    b.Property<bool>("IsMessageRead")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastMessageGeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Labubus");
                });

            modelBuilder.Entity("Labubu.Main.DAL.LabubuClothes", b =>
                {
                    b.Property<Guid>("LabubuId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClothesId")
                        .HasColumnType("uuid");

                    b.HasKey("LabubuId", "ClothesId");

                    b.HasIndex("ClothesId");

                    b.ToTable("LabubuClothes");
                });

            modelBuilder.Entity("Labubu.Main.DAL.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Labubu.Main.DAL.AchievementProgress", b =>
                {
                    b.HasOne("Labubu.Main.DAL.Achievement", "Achievement")
                        .WithMany("AchievementProgresses")
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Labubu.Main.DAL.Labubu", "Labubu")
                        .WithMany("AchievementProgresses")
                        .HasForeignKey("LabubuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("Labubu");
                });

            modelBuilder.Entity("Labubu.Main.DAL.GameSession", b =>
                {
                    b.HasOne("Labubu.Main.DAL.Game", "Game")
                        .WithMany("GameSessions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Labubu.Main.DAL.Labubu", "Labubu")
                        .WithMany("GameSessions")
                        .HasForeignKey("LabubuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Labubu");
                });

            modelBuilder.Entity("Labubu.Main.DAL.Labubu", b =>
                {
                    b.HasOne("Labubu.Main.DAL.User", "User")
                        .WithOne("Labubu")
                        .HasForeignKey("Labubu.Main.DAL.Labubu", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Labubu.Main.DAL.LabubuClothes", b =>
                {
                    b.HasOne("Labubu.Main.DAL.Clothes", "Clothes")
                        .WithMany()
                        .HasForeignKey("ClothesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Labubu.Main.DAL.Labubu", "Labubu")
                        .WithMany("LabubuClothes")
                        .HasForeignKey("LabubuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clothes");

                    b.Navigation("Labubu");
                });

            modelBuilder.Entity("Labubu.Main.DAL.Achievement", b =>
                {
                    b.Navigation("AchievementProgresses");
                });

            modelBuilder.Entity("Labubu.Main.DAL.Game", b =>
                {
                    b.Navigation("GameSessions");
                });

            modelBuilder.Entity("Labubu.Main.DAL.Labubu", b =>
                {
                    b.Navigation("AchievementProgresses");

                    b.Navigation("GameSessions");

                    b.Navigation("LabubuClothes");
                });

            modelBuilder.Entity("Labubu.Main.DAL.User", b =>
                {
                    b.Navigation("Labubu")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
